import { NotificationType } from "@/models/notifications";
import {
  AlertCircle,
  AlertTriangle,
  Bell,
  Crown,
  Film,
  Flame,
  Gift,
  Heart,
  KeyRound,
  LogIn,
  Medal,
  MessageCircle,
  Play,
  Settings,
  Sparkles,
  TrendingUp,
  User,
  Users,
  XCircle,
} from "lucide-react-native";
import React from "react";

export const notificationIcons: Record<NotificationType, React.ElementType> = {
  show_starting: Play,
  trending_room: TrendingUp,
  friend_joined: Heart,
  your_friend_joined: Heart,
  streak_reminder: Flame,
  private_room_member_joined: Users,
  private_room_member_removed: XCircle,
  private_room_deleted: AlertCircle,
  private_room_message: MessageCircle,
  subscription_activated: Crown,
  subscription_expired: Crown,
  subscription_cancelled: XCircle,
  subscription_grace_period: Gift,
  new_login_device: LogIn,
  password_changed: KeyRound,
  system_maintenance: Settings,
  account_update: User,
  welcome: Sparkles,
  welcome_to_showchats: Sparkles,
  feature_update: Bell,
  show_level_up: Film,
  badge_earned: Medal,
  security_alert: AlertTriangle,
};
